// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.6.1
// source: cmd/proto/BasicMessage.proto

package Primitive

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TranStatus int32

const (
	TranStatus_New         TranStatus = 0
	TranStatus_PreAccepted TranStatus = 1
	TranStatus_Accepted    TranStatus = 2
	TranStatus_Commited    TranStatus = 3
	TranStatus_Applied     TranStatus = 4
)

// Enum value maps for TranStatus.
var (
	TranStatus_name = map[int32]string{
		0: "New",
		1: "PreAccepted",
		2: "Accepted",
		3: "Commited",
		4: "Applied",
	}
	TranStatus_value = map[string]int32{
		"New":         0,
		"PreAccepted": 1,
		"Accepted":    2,
		"Commited":    3,
		"Applied":     4,
	}
)

func (x TranStatus) Enum() *TranStatus {
	p := new(TranStatus)
	*p = x
	return p
}

func (x TranStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TranStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_cmd_proto_BasicMessage_proto_enumTypes[0].Descriptor()
}

func (TranStatus) Type() protoreflect.EnumType {
	return &file_cmd_proto_BasicMessage_proto_enumTypes[0]
}

func (x TranStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TranStatus.Descriptor instead.
func (TranStatus) EnumDescriptor() ([]byte, []int) {
	return file_cmd_proto_BasicMessage_proto_rawDescGZIP(), []int{0}
}

type MsgType int32

const (
	MsgType_PreAccept   MsgType = 0
	MsgType_Accept      MsgType = 1
	MsgType_Commit      MsgType = 2
	MsgType_Read        MsgType = 3
	MsgType_Apply       MsgType = 4
	MsgType_Recover     MsgType = 5
	MsgType_Tick        MsgType = 6
	MsgType_PreAcceptOk MsgType = 7
	MsgType_AcceptOk    MsgType = 8
	MsgType_CommitOk    MsgType = 9
	MsgType_ReadOk      MsgType = 10
	MsgType_ApplyOk     MsgType = 11
	MsgType_RecoverOk   MsgType = 12
	MsgType_SubmitTrans MsgType = 13 // Used by the client to submit the transaction
	MsgType_HeartBeat   MsgType = 14
)

// Enum value maps for MsgType.
var (
	MsgType_name = map[int32]string{
		0:  "PreAccept",
		1:  "Accept",
		2:  "Commit",
		3:  "Read",
		4:  "Apply",
		5:  "Recover",
		6:  "Tick",
		7:  "PreAcceptOk",
		8:  "AcceptOk",
		9:  "CommitOk",
		10: "ReadOk",
		11: "ApplyOk",
		12: "RecoverOk",
		13: "SubmitTrans",
		14: "HeartBeat",
	}
	MsgType_value = map[string]int32{
		"PreAccept":   0,
		"Accept":      1,
		"Commit":      2,
		"Read":        3,
		"Apply":       4,
		"Recover":     5,
		"Tick":        6,
		"PreAcceptOk": 7,
		"AcceptOk":    8,
		"CommitOk":    9,
		"ReadOk":      10,
		"ApplyOk":     11,
		"RecoverOk":   12,
		"SubmitTrans": 13,
		"HeartBeat":   14,
	}
)

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}

func (x MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_cmd_proto_BasicMessage_proto_enumTypes[1].Descriptor()
}

func (MsgType) Type() protoreflect.EnumType {
	return &file_cmd_proto_BasicMessage_proto_enumTypes[1]
}

func (x MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgType.Descriptor instead.
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return file_cmd_proto_BasicMessage_proto_rawDescGZIP(), []int{1}
}

type TransTimestamp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimeStamp *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timeStamp,proto3" json:"timeStamp,omitempty"`
	Seq       int32                `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Id        int32                `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *TransTimestamp) Reset() {
	*x = TransTimestamp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_BasicMessage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransTimestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransTimestamp) ProtoMessage() {}

func (x *TransTimestamp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_BasicMessage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransTimestamp.ProtoReflect.Descriptor instead.
func (*TransTimestamp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_BasicMessage_proto_rawDescGZIP(), []int{0}
}

func (x *TransTimestamp) GetTimeStamp() *timestamp.Timestamp {
	if x != nil {
		return x.TimeStamp
	}
	return nil
}

func (x *TransTimestamp) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *TransTimestamp) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ReadOp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *ReadOp) Reset() {
	*x = ReadOp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_BasicMessage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadOp) ProtoMessage() {}

func (x *ReadOp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_BasicMessage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadOp.ProtoReflect.Descriptor instead.
func (*ReadOp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_BasicMessage_proto_rawDescGZIP(), []int{1}
}

func (x *ReadOp) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type SingleResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Val string `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"` // To write, it will be the write status
}

func (x *SingleResult) Reset() {
	*x = SingleResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_BasicMessage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SingleResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleResult) ProtoMessage() {}

func (x *SingleResult) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_BasicMessage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleResult.ProtoReflect.Descriptor instead.
func (*SingleResult) Descriptor() ([]byte, []int) {
	return file_cmd_proto_BasicMessage_proto_rawDescGZIP(), []int{2}
}

func (x *SingleResult) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SingleResult) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

// TODO Add more complex operation to WriteOp
type WriteOp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Val string `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
}

func (x *WriteOp) Reset() {
	*x = WriteOp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_BasicMessage_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteOp) ProtoMessage() {}

func (x *WriteOp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_BasicMessage_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteOp.ProtoReflect.Descriptor instead.
func (*WriteOp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_BasicMessage_proto_rawDescGZIP(), []int{3}
}

func (x *WriteOp) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *WriteOp) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res []string `protobuf:"bytes,1,rep,name=res,proto3" json:"res,omitempty"`
}

func (x *Result) Reset() {
	*x = Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_BasicMessage_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_BasicMessage_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_cmd_proto_BasicMessage_proto_rawDescGZIP(), []int{4}
}

func (x *Result) GetRes() []string {
	if x != nil {
		return x.Res
	}
	return nil
}

// TODO check if more fields are needed
type Deps struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//The id of conflicting transactions
	Ids []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
}

func (x *Deps) Reset() {
	*x = Deps{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_BasicMessage_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Deps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deps) ProtoMessage() {}

func (x *Deps) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_BasicMessage_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deps.ProtoReflect.Descriptor instead.
func (*Deps) Descriptor() ([]byte, []int) {
	return file_cmd_proto_BasicMessage_proto_rawDescGZIP(), []int{5}
}

func (x *Deps) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

// TODO design reads part and writes
type Trans struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//The following timestamp should be the t0, which should not be modified
	T0              *TransTimestamp `protobuf:"bytes,1,opt,name=t0,proto3" json:"t0,omitempty"`
	Reads           []*ReadOp       `protobuf:"bytes,2,rep,name=reads,proto3" json:"reads,omitempty"`
	Writes          []*WriteOp      `protobuf:"bytes,3,rep,name=writes,proto3" json:"writes,omitempty"`
	Id              string          `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"` // generated by t0, used to find transaction in the server side
	St              TranStatus      `protobuf:"varint,5,opt,name=st,proto3,enum=TranStatus" json:"st,omitempty"`
	ClientInfo      *NodeInfo       `protobuf:"bytes,6,opt,name=clientInfo,proto3" json:"clientInfo,omitempty"`
	CId             string          `protobuf:"bytes,7,opt,name=cId,proto3" json:"cId,omitempty"`                                 // This cId is assigned by the client, which is used retrieve results
	EleSize         int32           `protobuf:"varint,8,opt,name=eleSize,proto3" json:"eleSize,omitempty"`                        // Size of the electorates
	RelatedReplicas []int32         `protobuf:"varint,9,rep,packed,name=relatedReplicas,proto3" json:"relatedReplicas,omitempty"` // the id of the related replicas
	//The following is also the decided version of collectT in outer Trans
	ExT           *TransTimestamp `protobuf:"bytes,10,opt,name=ExT,proto3" json:"ExT,omitempty"`                             //Execution t, which is decided in the Accept phase
	RelatedShards []int32         `protobuf:"varint,11,rep,packed,name=relatedShards,proto3" json:"relatedShards,omitempty"` // Related shardId of this transaction
	Deps          *Deps           `protobuf:"bytes,12,opt,name=deps,proto3" json:"deps,omitempty"`                           // Store the decided deps, which is set in the send read phase
}

func (x *Trans) Reset() {
	*x = Trans{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_BasicMessage_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Trans) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trans) ProtoMessage() {}

func (x *Trans) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_BasicMessage_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trans.ProtoReflect.Descriptor instead.
func (*Trans) Descriptor() ([]byte, []int) {
	return file_cmd_proto_BasicMessage_proto_rawDescGZIP(), []int{6}
}

func (x *Trans) GetT0() *TransTimestamp {
	if x != nil {
		return x.T0
	}
	return nil
}

func (x *Trans) GetReads() []*ReadOp {
	if x != nil {
		return x.Reads
	}
	return nil
}

func (x *Trans) GetWrites() []*WriteOp {
	if x != nil {
		return x.Writes
	}
	return nil
}

func (x *Trans) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Trans) GetSt() TranStatus {
	if x != nil {
		return x.St
	}
	return TranStatus_New
}

func (x *Trans) GetClientInfo() *NodeInfo {
	if x != nil {
		return x.ClientInfo
	}
	return nil
}

func (x *Trans) GetCId() string {
	if x != nil {
		return x.CId
	}
	return ""
}

func (x *Trans) GetEleSize() int32 {
	if x != nil {
		return x.EleSize
	}
	return 0
}

func (x *Trans) GetRelatedReplicas() []int32 {
	if x != nil {
		return x.RelatedReplicas
	}
	return nil
}

func (x *Trans) GetExT() *TransTimestamp {
	if x != nil {
		return x.ExT
	}
	return nil
}

func (x *Trans) GetRelatedShards() []int32 {
	if x != nil {
		return x.RelatedShards
	}
	return nil
}

func (x *Trans) GetDeps() *Deps {
	if x != nil {
		return x.Deps
	}
	return nil
}

// Used for client to pass its info, so that coordinator know how to send back info
// My need to be separated to other nodes during PreAccept TODO
type NodeInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"` // ip:port
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_BasicMessage_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_BasicMessage_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_cmd_proto_BasicMessage_proto_rawDescGZIP(), []int{7}
}

func (x *NodeInfo) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type ShardInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Start    []byte  `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End      []byte  `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	ShardId  int32   `protobuf:"varint,3,opt,name=shardId,proto3" json:"shardId,omitempty"`
	Replicas []int32 `protobuf:"varint,4,rep,packed,name=replicas,proto3" json:"replicas,omitempty"`
}

func (x *ShardInfo) Reset() {
	*x = ShardInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_BasicMessage_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShardInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardInfo) ProtoMessage() {}

func (x *ShardInfo) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_BasicMessage_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardInfo.ProtoReflect.Descriptor instead.
func (*ShardInfo) Descriptor() ([]byte, []int) {
	return file_cmd_proto_BasicMessage_proto_rawDescGZIP(), []int{8}
}

func (x *ShardInfo) GetStart() []byte {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *ShardInfo) GetEnd() []byte {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *ShardInfo) GetShardId() int32 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *ShardInfo) GetReplicas() []int32 {
	if x != nil {
		return x.Replicas
	}
	return nil
}

// Used by the client to submit the trans
// TODO The coordinator should return the transactionId to the client at suitable time
type SubmitTransReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Trans *Trans `protobuf:"bytes,1,opt,name=trans,proto3" json:"trans,omitempty"`
}

func (x *SubmitTransReq) Reset() {
	*x = SubmitTransReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_BasicMessage_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitTransReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTransReq) ProtoMessage() {}

func (x *SubmitTransReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_BasicMessage_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTransReq.ProtoReflect.Descriptor instead.
func (*SubmitTransReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_BasicMessage_proto_rawDescGZIP(), []int{9}
}

func (x *SubmitTransReq) GetTrans() *Trans {
	if x != nil {
		return x.Trans
	}
	return nil
}

type PreAcceptReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Trans *Trans          `protobuf:"bytes,1,opt,name=trans,proto3" json:"trans,omitempty"`
	T0    *TransTimestamp `protobuf:"bytes,2,opt,name=t0,proto3" json:"t0,omitempty"`
}

func (x *PreAcceptReq) Reset() {
	*x = PreAcceptReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_BasicMessage_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PreAcceptReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreAcceptReq) ProtoMessage() {}

func (x *PreAcceptReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_BasicMessage_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreAcceptReq.ProtoReflect.Descriptor instead.
func (*PreAcceptReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_BasicMessage_proto_rawDescGZIP(), []int{10}
}

func (x *PreAcceptReq) GetTrans() *Trans {
	if x != nil {
		return x.Trans
	}
	return nil
}

func (x *PreAcceptReq) GetT0() *TransTimestamp {
	if x != nil {
		return x.T0
	}
	return nil
}

type PreAcceptResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	T       *TransTimestamp `protobuf:"bytes,1,opt,name=t,proto3" json:"t,omitempty"`
	Deps    *Deps           `protobuf:"bytes,2,opt,name=deps,proto3" json:"deps,omitempty"`
	TransId string          `protobuf:"bytes,3,opt,name=transId,proto3" json:"transId,omitempty"`
}

func (x *PreAcceptResp) Reset() {
	*x = PreAcceptResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_BasicMessage_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PreAcceptResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreAcceptResp) ProtoMessage() {}

func (x *PreAcceptResp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_BasicMessage_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreAcceptResp.ProtoReflect.Descriptor instead.
func (*PreAcceptResp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_BasicMessage_proto_rawDescGZIP(), []int{11}
}

func (x *PreAcceptResp) GetT() *TransTimestamp {
	if x != nil {
		return x.T
	}
	return nil
}

func (x *PreAcceptResp) GetDeps() *Deps {
	if x != nil {
		return x.Deps
	}
	return nil
}

func (x *PreAcceptResp) GetTransId() string {
	if x != nil {
		return x.TransId
	}
	return ""
}

type AcceptReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Trans *Trans          `protobuf:"bytes,1,opt,name=trans,proto3" json:"trans,omitempty"`
	ExT   *TransTimestamp `protobuf:"bytes,2,opt,name=exT,proto3" json:"exT,omitempty"`
	Deps  *Deps           `protobuf:"bytes,3,opt,name=deps,proto3" json:"deps,omitempty"`
}

func (x *AcceptReq) Reset() {
	*x = AcceptReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_BasicMessage_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcceptReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptReq) ProtoMessage() {}

func (x *AcceptReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_BasicMessage_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptReq.ProtoReflect.Descriptor instead.
func (*AcceptReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_BasicMessage_proto_rawDescGZIP(), []int{12}
}

func (x *AcceptReq) GetTrans() *Trans {
	if x != nil {
		return x.Trans
	}
	return nil
}

func (x *AcceptReq) GetExT() *TransTimestamp {
	if x != nil {
		return x.ExT
	}
	return nil
}

func (x *AcceptReq) GetDeps() *Deps {
	if x != nil {
		return x.Deps
	}
	return nil
}

type AcceptResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Deps    *Deps  `protobuf:"bytes,1,opt,name=deps,proto3" json:"deps,omitempty"`
	TransId string `protobuf:"bytes,2,opt,name=transId,proto3" json:"transId,omitempty"`
}

func (x *AcceptResp) Reset() {
	*x = AcceptResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_BasicMessage_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcceptResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptResp) ProtoMessage() {}

func (x *AcceptResp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_BasicMessage_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptResp.ProtoReflect.Descriptor instead.
func (*AcceptResp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_BasicMessage_proto_rawDescGZIP(), []int{13}
}

func (x *AcceptResp) GetDeps() *Deps {
	if x != nil {
		return x.Deps
	}
	return nil
}

func (x *AcceptResp) GetTransId() string {
	if x != nil {
		return x.TransId
	}
	return ""
}

type CommitReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Trans *Trans          `protobuf:"bytes,1,opt,name=trans,proto3" json:"trans,omitempty"`
	ExT   *TransTimestamp `protobuf:"bytes,2,opt,name=exT,proto3" json:"exT,omitempty"`
	Deps  *Deps           `protobuf:"bytes,3,opt,name=deps,proto3" json:"deps,omitempty"`
}

func (x *CommitReq) Reset() {
	*x = CommitReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_BasicMessage_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommitReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitReq) ProtoMessage() {}

func (x *CommitReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_BasicMessage_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitReq.ProtoReflect.Descriptor instead.
func (*CommitReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_BasicMessage_proto_rawDescGZIP(), []int{14}
}

func (x *CommitReq) GetTrans() *Trans {
	if x != nil {
		return x.Trans
	}
	return nil
}

func (x *CommitReq) GetExT() *TransTimestamp {
	if x != nil {
		return x.ExT
	}
	return nil
}

func (x *CommitReq) GetDeps() *Deps {
	if x != nil {
		return x.Deps
	}
	return nil
}

type ReadReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Trans *Trans          `protobuf:"bytes,1,opt,name=trans,proto3" json:"trans,omitempty"`
	ExT   *TransTimestamp `protobuf:"bytes,2,opt,name=exT,proto3" json:"exT,omitempty"`
	Deps  *Deps           `protobuf:"bytes,3,opt,name=deps,proto3" json:"deps,omitempty"`
}

func (x *ReadReq) Reset() {
	*x = ReadReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_BasicMessage_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadReq) ProtoMessage() {}

func (x *ReadReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_BasicMessage_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadReq.ProtoReflect.Descriptor instead.
func (*ReadReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_BasicMessage_proto_rawDescGZIP(), []int{15}
}

func (x *ReadReq) GetTrans() *Trans {
	if x != nil {
		return x.Trans
	}
	return nil
}

func (x *ReadReq) GetExT() *TransTimestamp {
	if x != nil {
		return x.ExT
	}
	return nil
}

func (x *ReadReq) GetDeps() *Deps {
	if x != nil {
		return x.Deps
	}
	return nil
}

type ReadResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res     []*SingleResult `protobuf:"bytes,1,rep,name=res,proto3" json:"res,omitempty"`
	TransId string          `protobuf:"bytes,2,opt,name=transId,proto3" json:"transId,omitempty"`
}

func (x *ReadResp) Reset() {
	*x = ReadResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_BasicMessage_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResp) ProtoMessage() {}

func (x *ReadResp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_BasicMessage_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResp.ProtoReflect.Descriptor instead.
func (*ReadResp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_BasicMessage_proto_rawDescGZIP(), []int{16}
}

func (x *ReadResp) GetRes() []*SingleResult {
	if x != nil {
		return x.Res
	}
	return nil
}

func (x *ReadResp) GetTransId() string {
	if x != nil {
		return x.TransId
	}
	return ""
}

type ApplyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Trans *Trans          `protobuf:"bytes,1,opt,name=trans,proto3" json:"trans,omitempty"`
	ExT   *TransTimestamp `protobuf:"bytes,2,opt,name=exT,proto3" json:"exT,omitempty"`
	DepsP *Deps           `protobuf:"bytes,3,opt,name=deps_p,json=depsP,proto3" json:"deps_p,omitempty"`
	Res   []*SingleResult `protobuf:"bytes,4,rep,name=res,proto3" json:"res,omitempty"`
}

func (x *ApplyReq) Reset() {
	*x = ApplyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_BasicMessage_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyReq) ProtoMessage() {}

func (x *ApplyReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_BasicMessage_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyReq.ProtoReflect.Descriptor instead.
func (*ApplyReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_BasicMessage_proto_rawDescGZIP(), []int{17}
}

func (x *ApplyReq) GetTrans() *Trans {
	if x != nil {
		return x.Trans
	}
	return nil
}

func (x *ApplyReq) GetExT() *TransTimestamp {
	if x != nil {
		return x.ExT
	}
	return nil
}

func (x *ApplyReq) GetDepsP() *Deps {
	if x != nil {
		return x.DepsP
	}
	return nil
}

func (x *ApplyReq) GetRes() []*SingleResult {
	if x != nil {
		return x.Res
	}
	return nil
}

type RecoverReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RecoverReq) Reset() {
	*x = RecoverReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_BasicMessage_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecoverReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoverReq) ProtoMessage() {}

func (x *RecoverReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_BasicMessage_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoverReq.ProtoReflect.Descriptor instead.
func (*RecoverReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_BasicMessage_proto_rawDescGZIP(), []int{18}
}

type RecoverResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RecoverResp) Reset() {
	*x = RecoverResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_BasicMessage_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecoverResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoverResp) ProtoMessage() {}

func (x *RecoverResp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_BasicMessage_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoverResp.ProtoReflect.Descriptor instead.
func (*RecoverResp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_BasicMessage_proto_rawDescGZIP(), []int{19}
}

// Tick Msg is used to update time and calculate for timeout
type TickMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimeStamp *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timeStamp,proto3" json:"timeStamp,omitempty"`
}

func (x *TickMsg) Reset() {
	*x = TickMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_BasicMessage_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TickMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickMsg) ProtoMessage() {}

func (x *TickMsg) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_BasicMessage_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickMsg.ProtoReflect.Descriptor instead.
func (*TickMsg) Descriptor() ([]byte, []int) {
	return file_cmd_proto_BasicMessage_proto_rawDescGZIP(), []int{20}
}

func (x *TickMsg) GetTimeStamp() *timestamp.Timestamp {
	if x != nil {
		return x.TimeStamp
	}
	return nil
}

type HeartbeatMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	To int32 `protobuf:"varint,1,opt,name=to,proto3" json:"to,omitempty"`
}

func (x *HeartbeatMsg) Reset() {
	*x = HeartbeatMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_BasicMessage_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartbeatMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatMsg) ProtoMessage() {}

func (x *HeartbeatMsg) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_BasicMessage_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatMsg.ProtoReflect.Descriptor instead.
func (*HeartbeatMsg) Descriptor() ([]byte, []int) {
	return file_cmd_proto_BasicMessage_proto_rawDescGZIP(), []int{21}
}

func (x *HeartbeatMsg) GetTo() int32 {
	if x != nil {
		return x.To
	}
	return 0
}

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type MsgType `protobuf:"varint,1,opt,name=type,proto3,enum=MsgType" json:"type,omitempty"`
	Data []byte  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	From int32   `protobuf:"varint,3,opt,name=from,proto3" json:"from,omitempty"`
	To   int32   `protobuf:"varint,4,opt,name=to,proto3" json:"to,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_BasicMessage_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_BasicMessage_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_cmd_proto_BasicMessage_proto_rawDescGZIP(), []int{22}
}

func (x *Message) GetType() MsgType {
	if x != nil {
		return x.Type
	}
	return MsgType_PreAccept
}

func (x *Message) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Message) GetFrom() int32 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *Message) GetTo() int32 {
	if x != nil {
		return x.To
	}
	return 0
}

var File_cmd_proto_BasicMessage_proto protoreflect.FileDescriptor

var file_cmd_proto_BasicMessage_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x63, 0x6d, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x42, 0x61, 0x73, 0x69,
	0x63, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6c, 0x0a, 0x0e,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x38,
	0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x1a, 0x0a, 0x06, 0x52, 0x65,
	0x61, 0x64, 0x4f, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x32, 0x0a, 0x0c, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x76, 0x61, 0x6c, 0x22, 0x2d, 0x0a, 0x07, 0x57, 0x72,
	0x69, 0x74, 0x65, 0x4f, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x76, 0x61, 0x6c, 0x22, 0x1a, 0x0a, 0x06, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x03, 0x72, 0x65, 0x73, 0x22, 0x18, 0x0a, 0x04, 0x44, 0x65, 0x70, 0x73, 0x12, 0x10, 0x0a,
	0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22,
	0xfb, 0x02, 0x0a, 0x05, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x12, 0x1f, 0x0a, 0x02, 0x74, 0x30, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x30, 0x12, 0x1d, 0x0a, 0x05, 0x72, 0x65,
	0x61, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x52, 0x65, 0x61, 0x64,
	0x4f, 0x70, 0x52, 0x05, 0x72, 0x65, 0x61, 0x64, 0x73, 0x12, 0x20, 0x0a, 0x06, 0x77, 0x72, 0x69,
	0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x57, 0x72, 0x69, 0x74,
	0x65, 0x4f, 0x70, 0x52, 0x06, 0x77, 0x72, 0x69, 0x74, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x02, 0x73,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x02, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x0a, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x4e,
	0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x49, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x63, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x65, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12,
	0x28, 0x0a, 0x0f, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x65, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63,
	0x61, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0f, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x65,
	0x64, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x73, 0x12, 0x21, 0x0a, 0x03, 0x45, 0x78, 0x54,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x03, 0x45, 0x78, 0x54, 0x12, 0x24, 0x0a, 0x0d,
	0x72, 0x65, 0x6c, 0x61, 0x74, 0x65, 0x64, 0x53, 0x68, 0x61, 0x72, 0x64, 0x73, 0x18, 0x0b, 0x20,
	0x03, 0x28, 0x05, 0x52, 0x0d, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x65, 0x64, 0x53, 0x68, 0x61, 0x72,
	0x64, 0x73, 0x12, 0x19, 0x0a, 0x04, 0x64, 0x65, 0x70, 0x73, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x05, 0x2e, 0x44, 0x65, 0x70, 0x73, 0x52, 0x04, 0x64, 0x65, 0x70, 0x73, 0x22, 0x1e, 0x0a,
	0x08, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x22, 0x69, 0x0a,
	0x09, 0x53, 0x68, 0x61, 0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x65,
	0x6e, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x68, 0x61, 0x72, 0x64, 0x49, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x73, 0x68, 0x61, 0x72, 0x64, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x05, 0x52, 0x08,
	0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x73, 0x22, 0x2e, 0x0a, 0x0e, 0x53, 0x75, 0x62, 0x6d,
	0x69, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x05, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x52, 0x05, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x22, 0x4d, 0x0a, 0x0c, 0x50, 0x72, 0x65, 0x41,
	0x63, 0x63, 0x65, 0x70, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x05, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x52,
	0x05, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x12, 0x1f, 0x0a, 0x02, 0x74, 0x30, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x30, 0x22, 0x63, 0x0a, 0x0d, 0x50, 0x72, 0x65, 0x41, 0x63,
	0x63, 0x65, 0x70, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1d, 0x0a, 0x01, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x01, 0x74, 0x12, 0x19, 0x0a, 0x04, 0x64, 0x65, 0x70, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x44, 0x65, 0x70, 0x73, 0x52, 0x04, 0x64, 0x65,
	0x70, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x49, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x49, 0x64, 0x22, 0x67, 0x0a, 0x09,
	0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x05, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x52, 0x05, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x12, 0x21, 0x0a, 0x03, 0x65, 0x78, 0x54, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x03, 0x65, 0x78, 0x54, 0x12, 0x19, 0x0a, 0x04, 0x64, 0x65,
	0x70, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x44, 0x65, 0x70, 0x73, 0x52,
	0x04, 0x64, 0x65, 0x70, 0x73, 0x22, 0x41, 0x0a, 0x0a, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x19, 0x0a, 0x04, 0x64, 0x65, 0x70, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x05, 0x2e, 0x44, 0x65, 0x70, 0x73, 0x52, 0x04, 0x64, 0x65, 0x70, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x49, 0x64, 0x22, 0x67, 0x0a, 0x09, 0x43, 0x6f, 0x6d, 0x6d,
	0x69, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x05, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x52, 0x05, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x12, 0x21, 0x0a, 0x03, 0x65, 0x78, 0x54, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x03, 0x65, 0x78, 0x54, 0x12, 0x19, 0x0a, 0x04, 0x64, 0x65, 0x70, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x44, 0x65, 0x70, 0x73, 0x52, 0x04, 0x64, 0x65, 0x70,
	0x73, 0x22, 0x65, 0x0a, 0x07, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x05,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x52, 0x05, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x12, 0x21, 0x0a, 0x03, 0x65, 0x78,
	0x54, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x03, 0x65, 0x78, 0x54, 0x12, 0x19, 0x0a,
	0x04, 0x64, 0x65, 0x70, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x44, 0x65,
	0x70, 0x73, 0x52, 0x04, 0x64, 0x65, 0x70, 0x73, 0x22, 0x45, 0x0a, 0x08, 0x52, 0x65, 0x61, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x1f, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x52, 0x03, 0x72, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x49, 0x64, 0x22,
	0x8a, 0x01, 0x0a, 0x08, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x05,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x52, 0x05, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x12, 0x21, 0x0a, 0x03, 0x65, 0x78,
	0x54, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x03, 0x65, 0x78, 0x54, 0x12, 0x1c, 0x0a,
	0x06, 0x64, 0x65, 0x70, 0x73, 0x5f, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e,
	0x44, 0x65, 0x70, 0x73, 0x52, 0x05, 0x64, 0x65, 0x70, 0x73, 0x50, 0x12, 0x1f, 0x0a, 0x03, 0x72,
	0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x53, 0x69, 0x6e, 0x67, 0x6c,
	0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x03, 0x72, 0x65, 0x73, 0x22, 0x0c, 0x0a, 0x0a,
	0x52, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x22, 0x0d, 0x0a, 0x0b, 0x52, 0x65,
	0x63, 0x6f, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x22, 0x43, 0x0a, 0x07, 0x54, 0x69, 0x63,
	0x6b, 0x4d, 0x73, 0x67, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x1e,
	0x0a, 0x0c, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x0e,
	0x0a, 0x02, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x74, 0x6f, 0x22, 0x5f,
	0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x08, 0x2e, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x66,
	0x72, 0x6f, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12,
	0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x74, 0x6f, 0x2a,
	0x4f, 0x0a, 0x0a, 0x54, 0x72, 0x61, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x07, 0x0a,
	0x03, 0x4e, 0x65, 0x77, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x50, 0x72, 0x65, 0x41, 0x63, 0x63,
	0x65, 0x70, 0x74, 0x65, 0x64, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x63, 0x63, 0x65, 0x70,
	0x74, 0x65, 0x64, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x65,
	0x64, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x64, 0x10, 0x04,
	0x2a, 0xd1, 0x01, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a, 0x09,
	0x50, 0x72, 0x65, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x41,
	0x63, 0x63, 0x65, 0x70, 0x74, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x6f, 0x6d, 0x6d, 0x69,
	0x74, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x52, 0x65, 0x61, 0x64, 0x10, 0x03, 0x12, 0x09, 0x0a,
	0x05, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x10, 0x04, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x65, 0x63, 0x6f,
	0x76, 0x65, 0x72, 0x10, 0x05, 0x12, 0x08, 0x0a, 0x04, 0x54, 0x69, 0x63, 0x6b, 0x10, 0x06, 0x12,
	0x0f, 0x0a, 0x0b, 0x50, 0x72, 0x65, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x4f, 0x6b, 0x10, 0x07,
	0x12, 0x0c, 0x0a, 0x08, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x4f, 0x6b, 0x10, 0x08, 0x12, 0x0c,
	0x0a, 0x08, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x4f, 0x6b, 0x10, 0x09, 0x12, 0x0a, 0x0a, 0x06,
	0x52, 0x65, 0x61, 0x64, 0x4f, 0x6b, 0x10, 0x0a, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x70, 0x70, 0x6c,
	0x79, 0x4f, 0x6b, 0x10, 0x0b, 0x12, 0x0d, 0x0a, 0x09, 0x52, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72,
	0x4f, 0x6b, 0x10, 0x0c, 0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x10, 0x0d, 0x12, 0x0d, 0x0a, 0x09, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65,
	0x61, 0x74, 0x10, 0x0e, 0x32, 0x3b, 0x0a, 0x0a, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61,
	0x74, 0x65, 0x12, 0x2d, 0x0a, 0x07, 0x73, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x12, 0x08, 0x2e,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22,
	0x00, 0x42, 0x0f, 0x5a, 0x0d, 0x63, 0x6d, 0x64, 0x2f, 0x50, 0x72, 0x69, 0x6d, 0x69, 0x74, 0x69,
	0x76, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cmd_proto_BasicMessage_proto_rawDescOnce sync.Once
	file_cmd_proto_BasicMessage_proto_rawDescData = file_cmd_proto_BasicMessage_proto_rawDesc
)

func file_cmd_proto_BasicMessage_proto_rawDescGZIP() []byte {
	file_cmd_proto_BasicMessage_proto_rawDescOnce.Do(func() {
		file_cmd_proto_BasicMessage_proto_rawDescData = protoimpl.X.CompressGZIP(file_cmd_proto_BasicMessage_proto_rawDescData)
	})
	return file_cmd_proto_BasicMessage_proto_rawDescData
}

var file_cmd_proto_BasicMessage_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_cmd_proto_BasicMessage_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_cmd_proto_BasicMessage_proto_goTypes = []interface{}{
	(TranStatus)(0),             // 0: TranStatus
	(MsgType)(0),                // 1: MsgType
	(*TransTimestamp)(nil),      // 2: TransTimestamp
	(*ReadOp)(nil),              // 3: ReadOp
	(*SingleResult)(nil),        // 4: SingleResult
	(*WriteOp)(nil),             // 5: WriteOp
	(*Result)(nil),              // 6: Result
	(*Deps)(nil),                // 7: Deps
	(*Trans)(nil),               // 8: Trans
	(*NodeInfo)(nil),            // 9: NodeInfo
	(*ShardInfo)(nil),           // 10: ShardInfo
	(*SubmitTransReq)(nil),      // 11: SubmitTransReq
	(*PreAcceptReq)(nil),        // 12: PreAcceptReq
	(*PreAcceptResp)(nil),       // 13: PreAcceptResp
	(*AcceptReq)(nil),           // 14: AcceptReq
	(*AcceptResp)(nil),          // 15: AcceptResp
	(*CommitReq)(nil),           // 16: CommitReq
	(*ReadReq)(nil),             // 17: ReadReq
	(*ReadResp)(nil),            // 18: ReadResp
	(*ApplyReq)(nil),            // 19: ApplyReq
	(*RecoverReq)(nil),          // 20: RecoverReq
	(*RecoverResp)(nil),         // 21: RecoverResp
	(*TickMsg)(nil),             // 22: TickMsg
	(*HeartbeatMsg)(nil),        // 23: HeartbeatMsg
	(*Message)(nil),             // 24: Message
	(*timestamp.Timestamp)(nil), // 25: google.protobuf.Timestamp
	(*empty.Empty)(nil),         // 26: google.protobuf.Empty
}
var file_cmd_proto_BasicMessage_proto_depIdxs = []int32{
	25, // 0: TransTimestamp.timeStamp:type_name -> google.protobuf.Timestamp
	2,  // 1: Trans.t0:type_name -> TransTimestamp
	3,  // 2: Trans.reads:type_name -> ReadOp
	5,  // 3: Trans.writes:type_name -> WriteOp
	0,  // 4: Trans.st:type_name -> TranStatus
	9,  // 5: Trans.clientInfo:type_name -> NodeInfo
	2,  // 6: Trans.ExT:type_name -> TransTimestamp
	7,  // 7: Trans.deps:type_name -> Deps
	8,  // 8: SubmitTransReq.trans:type_name -> Trans
	8,  // 9: PreAcceptReq.trans:type_name -> Trans
	2,  // 10: PreAcceptReq.t0:type_name -> TransTimestamp
	2,  // 11: PreAcceptResp.t:type_name -> TransTimestamp
	7,  // 12: PreAcceptResp.deps:type_name -> Deps
	8,  // 13: AcceptReq.trans:type_name -> Trans
	2,  // 14: AcceptReq.exT:type_name -> TransTimestamp
	7,  // 15: AcceptReq.deps:type_name -> Deps
	7,  // 16: AcceptResp.deps:type_name -> Deps
	8,  // 17: CommitReq.trans:type_name -> Trans
	2,  // 18: CommitReq.exT:type_name -> TransTimestamp
	7,  // 19: CommitReq.deps:type_name -> Deps
	8,  // 20: ReadReq.trans:type_name -> Trans
	2,  // 21: ReadReq.exT:type_name -> TransTimestamp
	7,  // 22: ReadReq.deps:type_name -> Deps
	4,  // 23: ReadResp.res:type_name -> SingleResult
	8,  // 24: ApplyReq.trans:type_name -> Trans
	2,  // 25: ApplyReq.exT:type_name -> TransTimestamp
	7,  // 26: ApplyReq.deps_p:type_name -> Deps
	4,  // 27: ApplyReq.res:type_name -> SingleResult
	25, // 28: TickMsg.timeStamp:type_name -> google.protobuf.Timestamp
	1,  // 29: Message.type:type_name -> MsgType
	24, // 30: Coordinate.sendReq:input_type -> Message
	26, // 31: Coordinate.sendReq:output_type -> google.protobuf.Empty
	31, // [31:32] is the sub-list for method output_type
	30, // [30:31] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_cmd_proto_BasicMessage_proto_init() }
func file_cmd_proto_BasicMessage_proto_init() {
	if File_cmd_proto_BasicMessage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cmd_proto_BasicMessage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransTimestamp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_BasicMessage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadOp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_BasicMessage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SingleResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_BasicMessage_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteOp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_BasicMessage_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_BasicMessage_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Deps); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_BasicMessage_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Trans); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_BasicMessage_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_BasicMessage_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShardInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_BasicMessage_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitTransReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_BasicMessage_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PreAcceptReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_BasicMessage_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PreAcceptResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_BasicMessage_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcceptReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_BasicMessage_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcceptResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_BasicMessage_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommitReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_BasicMessage_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_BasicMessage_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_BasicMessage_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApplyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_BasicMessage_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecoverReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_BasicMessage_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecoverResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_BasicMessage_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TickMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_BasicMessage_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartbeatMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_BasicMessage_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cmd_proto_BasicMessage_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cmd_proto_BasicMessage_proto_goTypes,
		DependencyIndexes: file_cmd_proto_BasicMessage_proto_depIdxs,
		EnumInfos:         file_cmd_proto_BasicMessage_proto_enumTypes,
		MessageInfos:      file_cmd_proto_BasicMessage_proto_msgTypes,
	}.Build()
	File_cmd_proto_BasicMessage_proto = out.File
	file_cmd_proto_BasicMessage_proto_rawDesc = nil
	file_cmd_proto_BasicMessage_proto_goTypes = nil
	file_cmd_proto_BasicMessage_proto_depIdxs = nil
}
