// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.22.2
// source: cmd/proto/BasicMessage.proto

package Primitive

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReqType int32

const (
	ReqType_PreAccept ReqType = 0
	ReqType_Accept    ReqType = 1
	ReqType_Commit    ReqType = 2
	ReqType_Read      ReqType = 3
	ReqType_Apply     ReqType = 4
	ReqType_Recover   ReqType = 5
	ReqType_Tick      ReqType = 6
)

// Enum value maps for ReqType.
var (
	ReqType_name = map[int32]string{
		0: "PreAccept",
		1: "Accept",
		2: "Commit",
		3: "Read",
		4: "Apply",
		5: "Recover",
		6: "Tick",
	}
	ReqType_value = map[string]int32{
		"PreAccept": 0,
		"Accept":    1,
		"Commit":    2,
		"Read":      3,
		"Apply":     4,
		"Recover":   5,
		"Tick":      6,
	}
)

func (x ReqType) Enum() *ReqType {
	p := new(ReqType)
	*p = x
	return p
}

func (x ReqType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReqType) Descriptor() protoreflect.EnumDescriptor {
	return file_cmd_proto_BasicMessage_proto_enumTypes[0].Descriptor()
}

func (ReqType) Type() protoreflect.EnumType {
	return &file_cmd_proto_BasicMessage_proto_enumTypes[0]
}

func (x ReqType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReqType.Descriptor instead.
func (ReqType) EnumDescriptor() ([]byte, []int) {
	return file_cmd_proto_BasicMessage_proto_rawDescGZIP(), []int{0}
}

type RespType int32

const (
	RespType_PreAcceptOk RespType = 0
	RespType_AcceptOk    RespType = 1
	RespType_CommitOk    RespType = 2
	RespType_ReadOk      RespType = 3
	RespType_ApplyOk     RespType = 4
	RespType_RecoverOk   RespType = 5
)

// Enum value maps for RespType.
var (
	RespType_name = map[int32]string{
		0: "PreAcceptOk",
		1: "AcceptOk",
		2: "CommitOk",
		3: "ReadOk",
		4: "ApplyOk",
		5: "RecoverOk",
	}
	RespType_value = map[string]int32{
		"PreAcceptOk": 0,
		"AcceptOk":    1,
		"CommitOk":    2,
		"ReadOk":      3,
		"ApplyOk":     4,
		"RecoverOk":   5,
	}
)

func (x RespType) Enum() *RespType {
	p := new(RespType)
	*p = x
	return p
}

func (x RespType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RespType) Descriptor() protoreflect.EnumDescriptor {
	return file_cmd_proto_BasicMessage_proto_enumTypes[1].Descriptor()
}

func (RespType) Type() protoreflect.EnumType {
	return &file_cmd_proto_BasicMessage_proto_enumTypes[1]
}

func (x RespType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RespType.Descriptor instead.
func (RespType) EnumDescriptor() ([]byte, []int) {
	return file_cmd_proto_BasicMessage_proto_rawDescGZIP(), []int{1}
}

type TransTimestamp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimeStamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timeStamp,proto3" json:"timeStamp,omitempty"`
	Seq       int32                  `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Id        int32                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *TransTimestamp) Reset() {
	*x = TransTimestamp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_BasicMessage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransTimestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransTimestamp) ProtoMessage() {}

func (x *TransTimestamp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_BasicMessage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransTimestamp.ProtoReflect.Descriptor instead.
func (*TransTimestamp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_BasicMessage_proto_rawDescGZIP(), []int{0}
}

func (x *TransTimestamp) GetTimeStamp() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeStamp
	}
	return nil
}

func (x *TransTimestamp) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *TransTimestamp) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ReadOp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *ReadOp) Reset() {
	*x = ReadOp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_BasicMessage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadOp) ProtoMessage() {}

func (x *ReadOp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_BasicMessage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadOp.ProtoReflect.Descriptor instead.
func (*ReadOp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_BasicMessage_proto_rawDescGZIP(), []int{1}
}

func (x *ReadOp) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// TODO Add more complex operation to WriteOp
type WriteOp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *WriteOp) Reset() {
	*x = WriteOp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_BasicMessage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteOp) ProtoMessage() {}

func (x *WriteOp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_BasicMessage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteOp.ProtoReflect.Descriptor instead.
func (*WriteOp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_BasicMessage_proto_rawDescGZIP(), []int{2}
}

func (x *WriteOp) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// TODO check if more fields are needed
type Deps struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The id of conflicting transactions
	Ids []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
}

func (x *Deps) Reset() {
	*x = Deps{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_BasicMessage_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Deps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deps) ProtoMessage() {}

func (x *Deps) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_BasicMessage_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deps.ProtoReflect.Descriptor instead.
func (*Deps) Descriptor() ([]byte, []int) {
	return file_cmd_proto_BasicMessage_proto_rawDescGZIP(), []int{3}
}

func (x *Deps) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

// TODO design reads part and writes
type Trans struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// TODO Check the specific meaning of this timestamp
	Timestamp *TransTimestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Reads     []*ReadOp       `protobuf:"bytes,2,rep,name=reads,proto3" json:"reads,omitempty"`
	Writes    []*WriteOp      `protobuf:"bytes,3,rep,name=writes,proto3" json:"writes,omitempty"`
	Id        string          `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Trans) Reset() {
	*x = Trans{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_BasicMessage_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Trans) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trans) ProtoMessage() {}

func (x *Trans) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_BasicMessage_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trans.ProtoReflect.Descriptor instead.
func (*Trans) Descriptor() ([]byte, []int) {
	return file_cmd_proto_BasicMessage_proto_rawDescGZIP(), []int{4}
}

func (x *Trans) GetTimestamp() *TransTimestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Trans) GetReads() []*ReadOp {
	if x != nil {
		return x.Reads
	}
	return nil
}

func (x *Trans) GetWrites() []*WriteOp {
	if x != nil {
		return x.Writes
	}
	return nil
}

func (x *Trans) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PreAcceptReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Trans *Trans          `protobuf:"bytes,1,opt,name=trans,proto3" json:"trans,omitempty"`
	T0    *TransTimestamp `protobuf:"bytes,2,opt,name=t0,proto3" json:"t0,omitempty"`
}

func (x *PreAcceptReq) Reset() {
	*x = PreAcceptReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_BasicMessage_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PreAcceptReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreAcceptReq) ProtoMessage() {}

func (x *PreAcceptReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_BasicMessage_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreAcceptReq.ProtoReflect.Descriptor instead.
func (*PreAcceptReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_BasicMessage_proto_rawDescGZIP(), []int{5}
}

func (x *PreAcceptReq) GetTrans() *Trans {
	if x != nil {
		return x.Trans
	}
	return nil
}

func (x *PreAcceptReq) GetT0() *TransTimestamp {
	if x != nil {
		return x.T0
	}
	return nil
}

type PreAcceptResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	T    *TransTimestamp `protobuf:"bytes,1,opt,name=t,proto3" json:"t,omitempty"`
	Deps *Deps           `protobuf:"bytes,2,opt,name=deps,proto3" json:"deps,omitempty"`
}

func (x *PreAcceptResp) Reset() {
	*x = PreAcceptResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_BasicMessage_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PreAcceptResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreAcceptResp) ProtoMessage() {}

func (x *PreAcceptResp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_BasicMessage_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreAcceptResp.ProtoReflect.Descriptor instead.
func (*PreAcceptResp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_BasicMessage_proto_rawDescGZIP(), []int{6}
}

func (x *PreAcceptResp) GetT() *TransTimestamp {
	if x != nil {
		return x.T
	}
	return nil
}

func (x *PreAcceptResp) GetDeps() *Deps {
	if x != nil {
		return x.Deps
	}
	return nil
}

type AcceptReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AcceptReq) Reset() {
	*x = AcceptReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_BasicMessage_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcceptReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptReq) ProtoMessage() {}

func (x *AcceptReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_BasicMessage_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptReq.ProtoReflect.Descriptor instead.
func (*AcceptReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_BasicMessage_proto_rawDescGZIP(), []int{7}
}

type AcceptResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AcceptResp) Reset() {
	*x = AcceptResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_BasicMessage_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcceptResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptResp) ProtoMessage() {}

func (x *AcceptResp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_BasicMessage_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptResp.ProtoReflect.Descriptor instead.
func (*AcceptResp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_BasicMessage_proto_rawDescGZIP(), []int{8}
}

type CommitReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CommitReq) Reset() {
	*x = CommitReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_BasicMessage_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommitReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitReq) ProtoMessage() {}

func (x *CommitReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_BasicMessage_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitReq.ProtoReflect.Descriptor instead.
func (*CommitReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_BasicMessage_proto_rawDescGZIP(), []int{9}
}

type ReadReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReadReq) Reset() {
	*x = ReadReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_BasicMessage_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadReq) ProtoMessage() {}

func (x *ReadReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_BasicMessage_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadReq.ProtoReflect.Descriptor instead.
func (*ReadReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_BasicMessage_proto_rawDescGZIP(), []int{10}
}

type ReadResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReadResp) Reset() {
	*x = ReadResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_BasicMessage_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResp) ProtoMessage() {}

func (x *ReadResp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_BasicMessage_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResp.ProtoReflect.Descriptor instead.
func (*ReadResp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_BasicMessage_proto_rawDescGZIP(), []int{11}
}

type ApplyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ApplyReq) Reset() {
	*x = ApplyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_BasicMessage_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyReq) ProtoMessage() {}

func (x *ApplyReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_BasicMessage_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyReq.ProtoReflect.Descriptor instead.
func (*ApplyReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_BasicMessage_proto_rawDescGZIP(), []int{12}
}

type RecoverReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RecoverReq) Reset() {
	*x = RecoverReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_BasicMessage_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecoverReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoverReq) ProtoMessage() {}

func (x *RecoverReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_BasicMessage_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoverReq.ProtoReflect.Descriptor instead.
func (*RecoverReq) Descriptor() ([]byte, []int) {
	return file_cmd_proto_BasicMessage_proto_rawDescGZIP(), []int{13}
}

type RecoverResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RecoverResp) Reset() {
	*x = RecoverResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_BasicMessage_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecoverResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoverResp) ProtoMessage() {}

func (x *RecoverResp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_BasicMessage_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoverResp.ProtoReflect.Descriptor instead.
func (*RecoverResp) Descriptor() ([]byte, []int) {
	return file_cmd_proto_BasicMessage_proto_rawDescGZIP(), []int{14}
}

// Tick Msg is used to update time and calculate for timeout
type TickMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimeStamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timeStamp,proto3" json:"timeStamp,omitempty"`
}

func (x *TickMsg) Reset() {
	*x = TickMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_BasicMessage_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TickMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickMsg) ProtoMessage() {}

func (x *TickMsg) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_BasicMessage_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickMsg.ProtoReflect.Descriptor instead.
func (*TickMsg) Descriptor() ([]byte, []int) {
	return file_cmd_proto_BasicMessage_proto_rawDescGZIP(), []int{15}
}

func (x *TickMsg) GetTimeStamp() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeStamp
	}
	return nil
}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type ReqType `protobuf:"varint,1,opt,name=type,proto3,enum=ReqType" json:"type,omitempty"`
	Data []byte  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_BasicMessage_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_BasicMessage_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_cmd_proto_BasicMessage_proto_rawDescGZIP(), []int{16}
}

func (x *Request) GetType() ReqType {
	if x != nil {
		return x.Type
	}
	return ReqType_PreAccept
}

func (x *Request) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type ReqType `protobuf:"varint,1,opt,name=type,proto3,enum=ReqType" json:"type,omitempty"`
	Data []byte  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_BasicMessage_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_BasicMessage_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_cmd_proto_BasicMessage_proto_rawDescGZIP(), []int{17}
}

func (x *Response) GetType() ReqType {
	if x != nil {
		return x.Type
	}
	return ReqType_PreAccept
}

func (x *Response) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_cmd_proto_BasicMessage_proto protoreflect.FileDescriptor

var file_cmd_proto_BasicMessage_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x63, 0x6d, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x42, 0x61, 0x73, 0x69,
	0x63, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x6c, 0x0a, 0x0e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x73,
	0x65, 0x71, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73, 0x65, 0x71, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x1a, 0x0a,
	0x06, 0x52, 0x65, 0x61, 0x64, 0x4f, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x1b, 0x0a, 0x07, 0x57, 0x72, 0x69,
	0x74, 0x65, 0x4f, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x18, 0x0a, 0x04, 0x44, 0x65, 0x70, 0x73, 0x12, 0x10,
	0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x69, 0x64, 0x73,
	0x22, 0x87, 0x01, 0x0a, 0x05, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x12, 0x2d, 0x0a, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1d, 0x0a, 0x05, 0x72, 0x65, 0x61,
	0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x4f,
	0x70, 0x52, 0x05, 0x72, 0x65, 0x61, 0x64, 0x73, 0x12, 0x20, 0x0a, 0x06, 0x77, 0x72, 0x69, 0x74,
	0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65,
	0x4f, 0x70, 0x52, 0x06, 0x77, 0x72, 0x69, 0x74, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x4d, 0x0a, 0x0c, 0x50, 0x72,
	0x65, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x05, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x52, 0x05, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x12, 0x1f, 0x0a, 0x02, 0x74, 0x30, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x30, 0x22, 0x49, 0x0a, 0x0d, 0x50, 0x72, 0x65,
	0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1d, 0x0a, 0x01, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x01, 0x74, 0x12, 0x19, 0x0a, 0x04, 0x64, 0x65, 0x70,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x44, 0x65, 0x70, 0x73, 0x52, 0x04,
	0x64, 0x65, 0x70, 0x73, 0x22, 0x0b, 0x0a, 0x09, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x52, 0x65,
	0x71, 0x22, 0x0c, 0x0a, 0x0a, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22,
	0x0b, 0x0a, 0x09, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71, 0x22, 0x09, 0x0a, 0x07,
	0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x22, 0x0a, 0x0a, 0x08, 0x52, 0x65, 0x61, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x22, 0x0a, 0x0a, 0x08, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x71, 0x22,
	0x0c, 0x0a, 0x0a, 0x52, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x22, 0x0d, 0x0a,
	0x0b, 0x52, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x22, 0x43, 0x0a, 0x07,
	0x54, 0x69, 0x63, 0x6b, 0x4d, 0x73, 0x67, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53,
	0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d,
	0x70, 0x22, 0x3b, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x08, 0x2e, 0x52, 0x65, 0x71,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x3c,
	0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x08, 0x2e, 0x52, 0x65, 0x71, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x2a, 0x5c, 0x0a, 0x07,
	0x52, 0x65, 0x71, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x50, 0x72, 0x65, 0x41, 0x63,
	0x63, 0x65, 0x70, 0x74, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74,
	0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x10, 0x02, 0x12, 0x08,
	0x0a, 0x04, 0x52, 0x65, 0x61, 0x64, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x70, 0x70, 0x6c,
	0x79, 0x10, 0x04, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x10, 0x05,
	0x12, 0x08, 0x0a, 0x04, 0x54, 0x69, 0x63, 0x6b, 0x10, 0x06, 0x2a, 0x5f, 0x0a, 0x08, 0x52, 0x65,
	0x73, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x50, 0x72, 0x65, 0x41, 0x63, 0x63,
	0x65, 0x70, 0x74, 0x4f, 0x6b, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x63, 0x63, 0x65, 0x70,
	0x74, 0x4f, 0x6b, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x4f,
	0x6b, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x65, 0x61, 0x64, 0x4f, 0x6b, 0x10, 0x03, 0x12,
	0x0b, 0x0a, 0x07, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x4f, 0x6b, 0x10, 0x04, 0x12, 0x0d, 0x0a, 0x09,
	0x52, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x4f, 0x6b, 0x10, 0x05, 0x32, 0x2e, 0x0a, 0x0a, 0x43,
	0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x12, 0x20, 0x0a, 0x07, 0x73, 0x65, 0x6e,
	0x64, 0x52, 0x65, 0x71, 0x12, 0x08, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x09,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0f, 0x5a, 0x0d, 0x63,
	0x6d, 0x64, 0x2f, 0x50, 0x72, 0x69, 0x6d, 0x69, 0x74, 0x69, 0x76, 0x65, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cmd_proto_BasicMessage_proto_rawDescOnce sync.Once
	file_cmd_proto_BasicMessage_proto_rawDescData = file_cmd_proto_BasicMessage_proto_rawDesc
)

func file_cmd_proto_BasicMessage_proto_rawDescGZIP() []byte {
	file_cmd_proto_BasicMessage_proto_rawDescOnce.Do(func() {
		file_cmd_proto_BasicMessage_proto_rawDescData = protoimpl.X.CompressGZIP(file_cmd_proto_BasicMessage_proto_rawDescData)
	})
	return file_cmd_proto_BasicMessage_proto_rawDescData
}

var file_cmd_proto_BasicMessage_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_cmd_proto_BasicMessage_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_cmd_proto_BasicMessage_proto_goTypes = []interface{}{
	(ReqType)(0),                  // 0: ReqType
	(RespType)(0),                 // 1: RespType
	(*TransTimestamp)(nil),        // 2: TransTimestamp
	(*ReadOp)(nil),                // 3: ReadOp
	(*WriteOp)(nil),               // 4: WriteOp
	(*Deps)(nil),                  // 5: Deps
	(*Trans)(nil),                 // 6: Trans
	(*PreAcceptReq)(nil),          // 7: PreAcceptReq
	(*PreAcceptResp)(nil),         // 8: PreAcceptResp
	(*AcceptReq)(nil),             // 9: AcceptReq
	(*AcceptResp)(nil),            // 10: AcceptResp
	(*CommitReq)(nil),             // 11: CommitReq
	(*ReadReq)(nil),               // 12: ReadReq
	(*ReadResp)(nil),              // 13: ReadResp
	(*ApplyReq)(nil),              // 14: ApplyReq
	(*RecoverReq)(nil),            // 15: RecoverReq
	(*RecoverResp)(nil),           // 16: RecoverResp
	(*TickMsg)(nil),               // 17: TickMsg
	(*Request)(nil),               // 18: Request
	(*Response)(nil),              // 19: Response
	(*timestamppb.Timestamp)(nil), // 20: google.protobuf.Timestamp
}
var file_cmd_proto_BasicMessage_proto_depIdxs = []int32{
	20, // 0: TransTimestamp.timeStamp:type_name -> google.protobuf.Timestamp
	2,  // 1: Trans.timestamp:type_name -> TransTimestamp
	3,  // 2: Trans.reads:type_name -> ReadOp
	4,  // 3: Trans.writes:type_name -> WriteOp
	6,  // 4: PreAcceptReq.trans:type_name -> Trans
	2,  // 5: PreAcceptReq.t0:type_name -> TransTimestamp
	2,  // 6: PreAcceptResp.t:type_name -> TransTimestamp
	5,  // 7: PreAcceptResp.deps:type_name -> Deps
	20, // 8: TickMsg.timeStamp:type_name -> google.protobuf.Timestamp
	0,  // 9: Request.type:type_name -> ReqType
	0,  // 10: Response.type:type_name -> ReqType
	18, // 11: Coordinate.sendReq:input_type -> Request
	19, // 12: Coordinate.sendReq:output_type -> Response
	12, // [12:13] is the sub-list for method output_type
	11, // [11:12] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_cmd_proto_BasicMessage_proto_init() }
func file_cmd_proto_BasicMessage_proto_init() {
	if File_cmd_proto_BasicMessage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cmd_proto_BasicMessage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransTimestamp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_BasicMessage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadOp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_BasicMessage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteOp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_BasicMessage_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Deps); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_BasicMessage_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Trans); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_BasicMessage_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PreAcceptReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_BasicMessage_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PreAcceptResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_BasicMessage_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcceptReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_BasicMessage_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcceptResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_BasicMessage_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommitReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_BasicMessage_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_BasicMessage_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_BasicMessage_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApplyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_BasicMessage_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecoverReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_BasicMessage_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecoverResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_BasicMessage_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TickMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_BasicMessage_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_BasicMessage_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cmd_proto_BasicMessage_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cmd_proto_BasicMessage_proto_goTypes,
		DependencyIndexes: file_cmd_proto_BasicMessage_proto_depIdxs,
		EnumInfos:         file_cmd_proto_BasicMessage_proto_enumTypes,
		MessageInfos:      file_cmd_proto_BasicMessage_proto_msgTypes,
	}.Build()
	File_cmd_proto_BasicMessage_proto = out.File
	file_cmd_proto_BasicMessage_proto_rawDesc = nil
	file_cmd_proto_BasicMessage_proto_goTypes = nil
	file_cmd_proto_BasicMessage_proto_depIdxs = nil
}
